### Problem 1

In [26]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [27]:
doc1 = 'Chapman university is in Orange County'
doc2 = 'Chapman university is a good university'
corpus = [doc1, doc2]

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()
X = vect.fit_transform(corpus)


transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
tfi_df = pd.DataFrame(tfidf.toarray(), columns = vect.get_feature_names())
tfi_df

chapman    county      good        in        is    orange  university
0  0.334712  0.470426  0.000000  0.470426  0.334712  0.470426    0.334712
1  0.354100  0.000000  0.497675  0.000000  0.354100  0.000000    0.708199

In [29]:
cv = CountVectorizer()
X = cv.fit(corpus)
print(cv.get_feature_names())
print(X.vocabulary_)

Y = cv.transform(corpus)
df = pd.DataFrame(Y.toarray(), columns = cv.get_feature_names())
df = df.T

['chapman', 'county', 'good', 'in', 'is', 'orange', 'university']
{'chapman': 0, 'university': 6, 'is': 4, 'in': 3, 'orange': 5, 'county': 1, 'good': 2}


In [30]:
sumDocu = np.zeros(Y.shape[0])
docFreq = np.zeros(Y.shape)

for i in range(len(corpus)):
    sumDocu[i] = sum(Y.toarray()[i])
    for j in range(len(Y.toarray()[i])):
        docFreq[i][j] = Y.toarray()[i][j]/sumDocu[i]
sklearn_df = pd.DataFrame(docFreq, columns= cv.get_feature_names())
sklearn_df

chapman    county  good        in        is    orange  university
0  0.166667  0.166667   0.0  0.166667  0.166667  0.166667    0.166667
1  0.200000  0.000000   0.2  0.000000  0.200000  0.000000    0.400000

### Problem 2

In [24]:
doc1 = 'The sky is blue'
doc2 = 'The sky is not blue'
corpus = [doc1, doc2]
vect = CountVectorizer()
X = vect.fit_transform(corpus)

transformer = TfidfTransformer()
tfidf = transformer.fit_transform(X)
tfi_df = pd.DataFrame(tfidf.toarray(), columns = vect.get_feature_names())
tfi_df

# the word "not" has the highest TF-IDF value

blue       is       not      sky      the
0  0.50000  0.50000  0.000000  0.50000  0.50000
1  0.40909  0.40909  0.574962  0.40909  0.40909

### Problem 3

In [6]:
from numpy import linalg as la

In [7]:
# Problem 3.1
m1 = np.array([[2,0],[0,5]])
m1_eigvals, m1_eigvects = la.eig(m1)
print("Eigvals:", m1_eigvals, "\n")
print("Eigvects:\n", m1_eigvects)

Eigvals: [2. 5.] 

Eigvects:
 [[1. 0.]
 [0. 1.]]


In [8]:
# Problem 3.2 
m2 = np.array([[4,1,6],[0,2,3],[0,0,9]])
m2_eigvals, m2_eigvects = la.eig(m2)
print("Eigvals:", m2_eigvals, "\n")
print("Eigvects:\n", m2_eigvects)

Eigvals: [4. 2. 9.] 

Eigvects:
 [[ 1.         -0.4472136   0.76337004]
 [ 0.          0.89442719  0.25445668]
 [ 0.          0.          0.59373225]]


In [9]:
# Problem 3.3 
m3 = np.array([[1,4,0,0],[0,2,0,0],[5,3,1,1],[4,7,2,2]])
m3_eigvals, m3_eigvects = la.eig(m3)
print("Eigvals:", m3_eigvals, "\n")
print("Eigvects:\n", m3_eigvects)

Eigvals: [0. 3. 1. 2.] 

Eigvects:
 [[ 0.          0.          0.19518001  0.10929207]
 [ 0.          0.          0.          0.02732302]
 [-0.70710678 -0.4472136   0.09759001 -0.31421469]
 [ 0.70710678 -0.89442719 -0.97590007 -0.94264406]]


In [10]:
# No you cannot compute the eigvals and eigvectors of a non-square matrix

### Problem 4

In [11]:
from scipy.linalg import svd
A = np.array([[5,7,21,32],[0,3,43,24],[2,36,95,84],[92,37,57,64]])
V, Sigma, Ustar = svd(A)
A_svd = V@np.diag(Sigma)@Ustar
print(A, "\n")
print(A_svd)

[[ 5  7 21 32]
 [ 0  3 43 24]
 [ 2 36 95 84]
 [92 37 57 64]] 

[[5.00000000e+00 7.00000000e+00 2.10000000e+01 3.20000000e+01]
 [3.55271368e-15 3.00000000e+00 4.30000000e+01 2.40000000e+01]
 [2.00000000e+00 3.60000000e+01 9.50000000e+01 8.40000000e+01]
 [9.20000000e+01 3.70000000e+01 5.70000000e+01 6.40000000e+01]]


### Problem 5

In [12]:
A[0] = A[1] + A[2]
A[-1] = A[1]

In [13]:
print(A)

[[  2  39 138 108]
 [  0   3  43  24]
 [  2  36  95  84]
 [  0   3  43  24]]


In [14]:
V, sigma, ustar = svd(A)
print("V:\n", V, "\n")
print("Sigma:", sigma, "\n")
print("UStar:\n", ustar)

V:
 [[-0.77161256 -0.06792686  0.63241345  0.00729593]
 [-0.20657449 -0.59776833 -0.30804962 -0.7107077 ]
 [-0.56503807  0.52984147 -0.63241345 -0.00729593]
 [-0.20657449 -0.59776833 -0.32436383  0.70341176]] 

Sigma: [2.32669952e+02 1.86197104e+01 1.34612623e-15 5.05418452e-17] 

UStar:
 [[-0.01148967 -0.22209016 -0.76471652 -0.60477483]
 [ 0.04961566  0.68951315 -0.56107449  0.45530794]
 [ 0.14600333  0.67562108  0.31568188 -0.65004933]
 [-0.98797232  0.13705376  0.02736804 -0.06616613]]


In [15]:
# The last 2 values of the Sigma matrix are zeros because 2 rows in A are dependent on each other.
# Row2 = Row4 