## CS530 Data Mining Homework 4 part 1

#### Question 1 (3 points): The Iris Dataset 

Load the Iris dataset using “datasets.load_iris()” from the Scikit-learn library. You can find the documentation of this dataset on Scikit-learn. Then Write a function that takes in two inputs:
1.	The data part of the Iris set without the labels
2.	k, the number of clusters
The function should implement the k-means algorithm as learned in class. Hence, the output of the function should be a list of cluster labels for each record of the Iris dataset, from 1 to k. 


In [2]:
from sklearn.datasets import load_iris
from scipy.spatial import distance
import numpy as np

iris = load_iris()
X = iris.data
    
def get_centroid(X,k):
    c1,c2,c3 = np.split(X,k)
    j = 0
    # Calculate the centroids for all 3 splits
    
    cent_a = np.array([np.mean(c1[:,j]), np.mean(c1[:,j+1]), np.mean(c1[:,j+2]), np.mean(c1[:,j+3])])
    cent_b = np.array([np.mean(c2[:,j]), np.mean(c2[:,j+1]), np.mean(c2[:,j+2]), np.mean(c2[:,j+3])])
    cent_c = np.array([np.mean(c3[:,j]), np.mean(c3[:,j+1]), np.mean(c3[:,j+2]), np.mean(c3[:,j+3])])
    
    return cent_a, cent_b, cent_c

def dist(x,y):
    d = distance.euclidean(x,y)
    return d

xnew = np.array([(19,19),(30,15),(25,25),(16,15),(19,12),(28,20)])
#dist(xnew[2],xnew[4])
c = dist(xnew[0],xnew[2])    
d = dist(xnew[0],xnew[5])
print(c)
print(d)

8.48528137423857
9.055385138137417


In [3]:
# Reassigning each point in X to new clusters.
def assign(X,centroid):
    new_cluster1 = [] 
    new_cluster2 = []
    new_cluster3 = []
    
# Iterating thru each array in X & re-sorting those arrays to new clusters 
# according to their distances from each centroid.

    for i in X:
        if dist(i,centroid[0]) < dist(i,centroid[1]) and dist(i,centroid[0]) < dist(i,centroid[2]):
            new_cluster1.append(i)
        elif dist(i,centroid[1]) < dist(i,centroid[0]) and dist(i,centroid[1]) < dist(i,centroid[2]):
            new_cluster2.append(i)
        else:
            new_cluster3.append(i)
            
# vstack 'stacks' the arrays instead of compiling them into a giant list.            
    n1 = np.vstack(new_cluster1)
    n2 = np.vstack(new_cluster2)
    n3 = np.vstack(new_cluster3)
    
# n1, n2, n3 are our new clusters.
    return n1, n2, n3

In [4]:
# This k_means function will return new split clusters.
def k_means(X, k=3):
    # You code goes here.
    centroids = get_centroid(X,k)
    n1,n2,n3 = assign(X,centroids)
    return n1,n2,n3

In [5]:
# a,b,c are the 3 new clusters
a,b,c = k_means(X, k = 3)
centroids = get_centroid(X,3)
centroids

(array([5.006, 3.428, 1.462, 0.246]),
 array([5.936, 2.77 , 4.26 , 1.326]),
 array([6.588, 2.974, 5.552, 2.026]))